104: Named Pipes 翻訳
ymotongpoo/erlang-in-anger pull request #18
Opened 2018-06-21 04:09 UTC by yaoshimax

## 翻訳スコープ
- 4章4節「Named Pipes」

## マージ目安
以下のどちらかが達成されたらマージしようと思ってます

- [ ] 誰か１人からLGTMをもらう

もしくは、

- [ ] 2018/06/22 12:00(JST) をすぎる
- [ ] このPRの向き先がjapaneseブランチになっている（＝前の節が全てマージ済）
- [ ] 訳者の不安な部分が解消される（＝TODOコメントがなくなる）

2018-06-21 05:36 UTC, ymotongpoo commented on 104-connecting-ja.tex
> +% A little known way to connect with an Erlang node that requires no explicit distribution is through named pipes.
@shino ここの distribution どう訳しましょう

2018-06-21 05:41 UTC, ymotongpoo requested changes
検討が必要だと思う箇所が数カ所ありました

2018-06-21 05:41 UTC, ymotongpoo commented on 104-connecting-ja.tex
> +これはErlangを\app{run\_erl}使って起動すれば実現できます。\app{run\_erl}が名前付きパイプ用にErlangをラップしてくれます\footnote{\command{"erl"}が実行されるコマンドです。引数はその後に追加できます。例えば\command{"erl +K true"}でカーネルポーリングが有効になります。}。
"wraps Erlang in a named pipe" というのが「名前付きパイプ用にErlangをラップ」という訳になるのは違和感があります。「名前付きパイプの中にErlangをラップする」というニュアンスが伝わってきません。

2018-06-21 05:56 UTC, shino commented on 104-connecting-ja.tex
> +% A little known way to connect with an Erlang node that requires no explicit distribution is through named pipes.
ここは disterl (distributed Erlang) の意味での distribution なので分散でいいかと思います。

2018-06-21 14:20 UTC, yaoshimax commented on 104-connecting-ja.tex
> +% A little known way to connect with an Erlang node that requires no explicit distribution is through named pipes.
ありがとうございます、少し文章見直しました。
分散を(明示的に)使わず～というと「使う」の対象が抽象的に感じたので、
分散Erlangを明示的に使わず～としてみましたが、いかがでしょうか？ https://github.com/ymotongpoo/erlang-in-anger/pull/18/commits/18e6f1c09e43d67b3165ecd70bf4dd6c85b32b7c

2018-06-21 14:21 UTC, yaoshimax commented on 104-connecting-ja.tex
> +これはErlangを\app{run\_erl}使って起動すれば実現できます。\app{run\_erl}が名前付きパイプ用にErlangをラップしてくれます\footnote{\command{"erl"}が実行されるコマンドです。引数はその後に追加できます。例えば\command{"erl +K true"}でカーネルポーリングが有効になります。}。
確かにこの訳だと「in」のニュアンスが何一つ表現されてないですね。
上で書かれていた
> 「名前付きパイプの中にErlangをラップする」

がそのままぴったし当てはまる様に感じたので、そのように変更しました https://github.com/ymotongpoo/erlang-in-anger/pull/18/commits/18e6f1c09e43d67b3165ecd70bf4dd6c85b32b7c

2018-06-21 23:00 UTC, shino commented on 104-connecting-ja.tex
> +% A little known way to connect with an Erlang node that requires no explicit distribution is through named pipes.
"分散 Erlang" のほうがより良いと思います。原文はちょっとハイコンテキストに感じていたので。

👍

2018-06-21 23:01 UTC, shino commented
👍 from me!

2018-06-22 03:08 UTC, yaoshimax commented
ご指摘点には一通り対応してあると思いますのでこちらマージしてしまいます、レビューのほどありがとうございました！

2018-06-22 03:09 UTC, merged