103: 3.3 Discarding Dataの導入部分翻訳
ymotongpoo/erlang-in-anger pull request #22
Opened 2018-06-21 14:04 UTC by e-koma

## 翻訳スコープ
- 3.3 章 Discarding DataのIntroduction部分です。

2018-06-21 15:09 UTC, ymotongpoo requested changes
一文訳出が難しいところがあるので、再確認お願いします

2018-06-21 15:09 UTC, ymotongpoo commented on 103-overload-ja.tex
> +これは全ての人が目を背けたくなる悲しい現実です。プログラマーや、ソフトウェアエンジニア、そしてコンピュータサイエンティストは、不要なデータは消去し、有用なデータはすべて保持するよう学んできています。諦めてはいけません、成功は最適化によってもたらされます。
最終的には似たニュアンスになるのとは思うのですが、"not giving up"は直前の"through"にかかるものなので、トーンとしてもうちょっと冷静な雰囲気を感じます。

2018-06-21 15:09 UTC, ymotongpoo commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、出力速度よりも速くデータを受信する場合もあります。場合によっては、ブロックした \emph{後の} コンポーネントが。
「場合によっては、ブロックした後のコンポーネントが。」ここは誤訳になっていると思います。

"It's the component \emph{after} it that blocks"の最初の it は直前の文の a point that 〜 以下を指していて、最後の it は the Erlang system で、また blocks は the component after it にかかっているので、一文全体だと「データの入力のほうが出力より速くなってしまっているような点が、Erlangシステムよりもあとにあるブロックしているコンポーネントだったりします」という形になると思います。

2018-06-22 01:49 UTC, e-koma commented on 103-overload-ja.tex
> +これは全ての人が目を背けたくなる悲しい現実です。プログラマーや、ソフトウェアエンジニア、そしてコンピュータサイエンティストは、不要なデータは消去し、有用なデータはすべて保持するよう学んできています。諦めてはいけません、成功は最適化によってもたらされます。
あーなるほど！！
では「諦めない最適化」＝「地道な最適化」として
「成功は地道な最適化によってもたらされます。」ぐらいのニュアンスに直します。

ありがとうございます。

2018-06-22 01:55 UTC, e-koma commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、出力速度よりも速くデータを受信する場合もあります。場合によっては、ブロックした \emph{後の} コンポーネントが。
レビューありがとうございます！
「後のコンポーネント = Erlangシステムの後ろに控えているバックエンドノード」と理解し読んだのですが、意訳が難しく直訳になった結果こうなってしまいました。。。

ちょっと頭の中を整理します。。。

2018-06-22 02:01 UTC, e-koma commented on 103-overload-ja.tex
> +これは全ての人が目を背けたくなる悲しい現実です。プログラマーや、ソフトウェアエンジニア、そしてコンピュータサイエンティストは、不要なデータは消去し、有用なデータはすべて保持するよう学んできています。諦めてはいけません、成功は最適化によってもたらされます。
むーん、そしてこの「Success」を意訳したい気持ちが出てきました。

文脈を考えると、
「Erlangシステムが大量トラフィックを問題なくさばける状態」のことをSuccessと一言で表しているかと思うので。

意訳しすぎ感はありますが、意味は通るかと思います。

2018-06-22 02:12 UTC, e-koma commented on 103-overload-ja.tex
> +これは全ての人が目を背けたくなる悲しい現実です。プログラマーや、ソフトウェアエンジニア、そしてコンピュータサイエンティストは、不要なデータは消去し、有用なデータはすべて保持するよう学んできています。諦めてはいけません、成功は最適化によってもたらされます。
候補としてはこんな感じです。
```
これは全ての人が目を背けたくなる悲しい現実です。プログラマーや、ソフトウェアエンジニア、そしてコンピュータサイエンティストは、不要なデータは消去し、有用なデータはすべて保持するよう学んできています。地道な最適化をすることにより、Erlangシステムは流入データを問題なく処理できる状態になります。
```

2018-06-22 02:42 UTC, e-koma commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、出力速度よりも速くデータを受信する場合もあります。場合によっては、ブロックした \emph{後の} コンポーネントが。
整理done

```
しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、後ろに控えるコンポーネントがブロックし、出力よりもデータ入力の方が速くなることもあります。
```
でいきます！

2018-06-22 02:58 UTC, e-koma commented
ほんのり意訳で修正してみました:bow:

2018-06-22 06:49 UTC, hykw commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、Erlangシステムの \emph{後ろ} に控えるコンポーネントがブロックし、出力よりもデータ入力の方が速くなることもあります。
原文、比喩的でわかりにくいですね。。。たぶんこの does は done の間違いですね（つまり reached の代名詞)。

直訳すると、「あるポイント(≒ 世界)が存在していてて、そこでは入力データが出力データよりも速いレートで到達している。そこの場所ではコンポーネントはブロックする」ということなので、Erlangが十分な速度で処理できるとしても、出力よりも入力の方が速いこともある、だから場合によってはコンポーネントがブロックすることもある、という意味だと思います。

2018-06-23 06:45 UTC, e-koma commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、Erlangシステムの \emph{後ろ} に控えるコンポーネントがブロックし、出力よりもデータ入力の方が速くなることもあります。
@hykw 
すみません、反応遅れました！
んんんなるほど…。

- `Erlang system on its own is able to do everything fast enough.`
  - everythingを十分高速に処理している.
- `It's the component \emph{after} it that blocks.`
  - Erlangシステムの **後の** コンポーネントがブロックする

の2点から、ここで言うコンポーネントとはErlang Systemの後ろに控えているデータベース等のことのように思えるんですが、いかがでしょう。。。？

データベース等が詰まるから、Erlangシステム自体が十分に高速に処理できるようにチューニングできていても、バックエンド起因で詰まる、ということを言いたいのだと思ったのですが。。。

2018-06-23 07:29 UTC, hykw commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、Erlangシステムの \emph{後ろ} に控えるコンポーネントがブロックし、出力よりもデータ入力の方が速くなることもあります。
あー、すいません。 after it を完全に読み落としてました。
おっしゃる通りですね。なので、after it は Erlang の後ろにあるDBやら何やらで詰まるということですね。

2018-06-23 07:32 UTC, e-koma commented on 103-overload-ja.tex
> +しかし、Erlangシステム自身が全てのデータを十分な速度で処理できたとしても、Erlangシステムの \emph{後ろ} に控えるコンポーネントがブロックし、出力よりもデータ入力の方が速くなることもあります。
ではこのままで進めます。
レビューありがとうございます！:pray:

2018-06-23 14:02 UTC, shino commented on 103-overload-ja.tex
> +Erlangシステム外から流入速度を落とせず、かつスケールアップもできない場合、データをドロップさせるか、クラッシュさせる必要があります（ほとんどの場合、処理中のデータですが、強制的に）。
outside of ですが、「から」というよりは「~以外」のほうが適切な気がします。

    outside of: ～の他に、～の外側へ、～を除いて、～を別とすれば

https://eow.alc.co.jp/search?q=Outside+of

2018-06-23 14:06 UTC, shino commented on 103-overload-ja.tex
> +Erlangシステム外から流入速度を落とせず、かつスケールアップもできない場合、データをドロップさせるか、クラッシュさせる必要があります（ほとんどの場合、処理中のデータですが、強制的に）。
> （ほとんどの場合、処理中のデータですが、強制的に）。

drop or crash と言っているところの "or" が exclusive ではない or になっているのを皮肉気味にコメントしているように感じました。
意訳的に書くと、crash を which で受けているので、「結局それ(=クラッシュ)でも大抵の場合は、処理中のデータをより乱暴にドロップします」という流れになるのかなと。

2018-06-23 14:54 UTC, shino commented
上の小さな2点を除いて 👍 from me.

2018-06-24 16:55 UTC, e-koma commented on 103-overload-ja.tex
> +Erlangシステム外から流入速度を落とせず、かつスケールアップもできない場合、データをドロップさせるか、クラッシュさせる必要があります（ほとんどの場合、処理中のデータですが、強制的に）。
なるほど、ありがとうございます！

2018-06-24 17:11 UTC, e-koma commented on 103-overload-ja.tex
> +Erlangシステム外から流入速度を落とせず、かつスケールアップもできない場合、データをドロップさせるか、クラッシュさせる必要があります（ほとんどの場合、処理中のデータですが、強制的に）。
なるほど、、！！！
クラッシュの後ろに補足文として追加しました。
ありがとうございます:pray:

```
データをドロップさせるか、クラッシュ（結局それでも大抵の場合は、処理中のデータをより乱暴にドロップ）させる必要があります。
```

2018-06-25 02:45 UTC, e-koma commented
(書くの遅れたw)
ありがとうございます！修正しました！

2018-06-26 03:21 UTC, e-koma commented
マージしてよければマージします〜

2018-06-26 12:00 UTC, ymotongpoo approved these changes

2018-06-26 12:01 UTC, ymotongpoo commented
マージどうぞ〜

2018-06-26 12:37 UTC, merged