108: 8.1 Profiling and Reduction Counts 訳
ymotongpoo/erlang-in-anger pull request #27
Opened 2018-06-22 01:25 UTC by tkyshm

## 翻訳スコープ
- 8.1「Profile and Reduction Counts」

気になっている点等はインラインでコメントしていきます.

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +\chapter{CPUとスケジューラの高負荷}
CPU Hogsはスラングらしい. CPUリソースを食いつぶしているとか、高い負荷がかかっているような意味で用いられている様子.

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +ノードから抜け出す重要な操作ができなくなることがあります。
後半部分、制限という言葉を直訳せずに、できなくなると訳しましたが、問題ないかどうか。
(また、意味はそもそも間違ってないか。)

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
この文章の訳は自信がないです。

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +前述したとおり、Erlangコード内の問題箇所を特定するアプローチは主に二つあります。一つは、古い標準のプロファイリングルーチンで、次に示すアプリケーションを利用することがあるでしょう。\footnote{これらのプロファイラは殆ど制限なくErlangのトレース機能を使って動作します。そのため、ランタイム上のアプリケーションのパフォーマンスに影響します。本番環境では使わないほうが良いでしょう。}
プロファイリングルーチン、という言葉はあるかどうか。

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> + \item \otpapp{eprof}、\footnote{\href{http://www.erlang.org/doc/man/eprof.html}{http://www.erlang.org/doc/man/eprof.html}}一番古いErlangのプロファイラです。おおよそのパーセンテージ値とその所要時間を結果として出します。
パーセンテージだけでもよさそうかもしれない。

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +新しいプロファイラの一つです。対象のコードの深い呼び出しシーケンスやホットスポットを可視化するFlame Graphsを生成します。
Flame Graphsは固有名詞かと思ったので、大文字にしてしまいましたが、適切な日本語訳があればそれにしようと思います。

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
日本語として少しぎこちなさがあるかもと感じてますが、どうでしょうか。

2018-06-22 09:29 UTC, tkyshm commented on 108-cpu-ja.tex
> +ただし、集中化したグローバルの状態（プロセス辞書やETSテーブルなど）だけは、だいたい変更が必要になります。
僕の見聞が狭いだけかもですが、集中化という言葉は余り聞いたことないなと感じてます。ハイセンスな言葉があれば修正したいです。

2018-06-22 09:34 UTC, y-yu commented
権限の問題で、僕が代理でPRタイトルの`[WIP]`をはずします。

2018-06-22 12:11 UTC, hykw commented on 108-cpu-ja.tex
> +\chapter{CPUとスケジューラの高負荷}
hog が「なんでもガツガツ食べる豚みたいな何か」のことで、hog と組み合わせの表現を結構見ます（とはいえ、cpu hog がしっくり来る訳は難しいですね。スラングによせるなら、CPUとスケジューラを食いつぶす香具師とかなんでしょうが）。

2018-06-22 12:16 UTC, hykw commented on 108-cpu-ja.tex
> +ノードから抜け出す重要な操作ができなくなることがあります。
get out of a node で取り出されるのは性能(work)ですね。つまりCPUが枯渇するとそれがボトルネックになって、ノードから取り出せる最大性能を制限しちゃう（＝つまり、最大性能を引き出せない）という意味かと。

2018-06-22 12:21 UTC, hykw commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
ここの basic は何でしょうね。。。piece of code は piece of cake のもじりなんでしょうが。。。全体を見ると、そんなの基本だよ（= すごく簡単だよ）という意味のように読めますね。

2018-06-22 12:22 UTC, hykw commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
真ん中の文は、プロセスレジストリとかETSテーブルはノード内でglobalなリソースなので、分散したらコード変更してどうにかしなきゃいけない、ということを言ってるかと。

2018-06-22 12:24 UTC, hykw commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
「finding a state-replication scheme that's suitable」は状態をレプリケーションする適切な方法を見つける（探す）ですかね。

2018-06-22 12:28 UTC, hykw commented on 108-cpu-ja.tex
> +前述したとおり、Erlangコード内の問題箇所を特定するアプローチは主に二つあります。一つは、古い標準のプロファイリングルーチンで、次に示すアプリケーションを利用することがあるでしょう。\footnote{これらのプロファイラは殆ど制限なくErlangのトレース機能を使って動作します。そのため、ランタイム上のアプリケーションのパフォーマンスに影響します。本番環境では使わないほうが良いでしょう。}
> 一つは、古い標準のプロファイリングルーチンで、次に示すアプリケーションを利用することがあるでしょう。
routine は手順ですかね。
試訳だと「一つは、次に示すアプリケーションを利用するような、古い標準的なプロファイリングの方法です」

2018-06-22 12:32 UTC, hykw commented on 108-cpu-ja.tex
> +ただし、集中化したグローバルの状態（プロセス辞書やETSテーブルなど）だけは、だいたい変更が必要になります。
プロセスレジストリとかETSテーブルはノード内でglobalなリソースなので、分散したらコード変更してどうにかしなきゃいけない、ということを言ってるかと。

2018-06-22 12:33 UTC, hykw commented on 108-cpu-ja.tex
> +ノードから抜け出す重要な操作ができなくなることがあります。
ここの basic は何でしょうね。。。piece of code は piece of cake のもじりなんでしょうが。。。全体を見ると、そんなの基本だよ（= すごく簡単だよ）という意味のように読めますね。

2018-06-22 12:35 UTC, hykw commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
並行→並行稼動 でしょうか。

2018-06-22 12:36 UTC, hykw commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
並行→並行稼動 でしょうか。

2018-06-22 12:39 UTC, hykw commented on 108-cpu-ja.tex
> +既存のアプローチは大体限られており、コード内にある場合はプロファイリングとリダクションカウント\footnote{プロセスごとにリダクションというカウンタがあり、このカウンターは通常一つの各関数呼び出しでインクリメントされます。このリダクション回数が最大値に達した時、コンテキストスイッチが発生します。例えば、 Erlang/OTP R12B ではリダクションの最大値は2000です。}を確認する二
http://erlang.org/doc/man/erlang.html#bump_reductions-1 へのリンクがあってもいいかもしれません。

2018-06-22 12:40 UTC, hykw commented on 108-cpu-ja.tex
> + \item \otpapp{eprof}、\footnote{\href{http://www.erlang.org/doc/man/eprof.html}{http://www.erlang.org/doc/man/eprof.html}}一番古いErlangのプロファイラです。おおよそのパーセンテージ値とその所要時間を結果として出します。
定訳は「パーセント値」かと。

2018-06-22 12:43 UTC, hykw commented on 108-cpu-ja.tex
> +新しいプロファイラの一つです。対象のコードの深い呼び出しシーケンスやホットスポットを可視化するFlame Graphsを生成します。
👍

2018-06-23 07:37 UTC, tkyshm commented on 108-cpu-ja.tex
> +前述したとおり、Erlangコード内の問題箇所を特定するアプローチは主に二つあります。一つは、古い標準のプロファイリングルーチンで、次に示すアプリケーションを利用することがあるでしょう。\footnote{これらのプロファイラは殆ど制限なくErlangのトレース機能を使って動作します。そのため、ランタイム上のアプリケーションのパフォーマンスに影響します。本番環境では使わないほうが良いでしょう。}
手順（方法）とそのままルーチンと訳すかで悩んだので、頂いたコメントに寄せたいと思います。

2018-06-23 07:38 UTC, tkyshm commented on 108-cpu-ja.tex
> +既存のアプローチは大体限られており、コード内にある場合はプロファイリングとリダクションカウント\footnote{プロセスごとにリダクションというカウンタがあり、このカウンターは通常一つの各関数呼び出しでインクリメントされます。このリダクション回数が最大値に達した時、コンテキストスイッチが発生します。例えば、 Erlang/OTP R12B ではリダクションの最大値は2000です。}を確認する二
あ、コメント付け忘れてました。参照リンクについて記載があったほうが良いかどうかというのを囲うとしてました。コメントで指摘ありましたので載せようと思います。

2018-06-23 07:40 UTC, tkyshm commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
並行稼働、並行する、どちらが良さそうか、他のレビューの意見も聞いて判断しようかと思います。

2018-06-23 07:43 UTC, tkyshm commented on 108-cpu-ja.tex
> +ただし、集中化したグローバルの状態（プロセス辞書やETSテーブルなど）だけは、だいたい変更が必要になります。
ここで言いたいことは、まさにコメントのとおりなので、そのように訳したほうが分かりやすくて良いので修正します。

2018-06-23 07:52 UTC, tkyshm commented on 108-cpu-ja.tex
> +\chapter{CPUとスケジューラの高負荷}
ニュアンスを含めて訳すと、食いつぶす云々と訳すのがたしかにそうだなと思いました。
章の名前なのでシュッとした感じになるのが良いかなと思いましたので高負荷という感じに収めてみましたが、他の方の意見も聞いてみて、ベターな言い回しがあれば修正したいと思います.

2018-06-23 07:58 UTC, shino commented on 108-cpu-ja.tex
> +\chapter{CPUとスケジューラの高負荷}
「独占」「独り占め」という訳もあるようです。

hog - 日本語翻訳　–　Linguee辞書
https://www.linguee.jp/%E8%8B%B1%E8%AA%9E-%E6%97%A5%E6%9C%AC%E8%AA%9E/%E7%BF%BB%E8%A8%B3/hog.html

動詞的に使う場合は「CPUをガメる」とかも(ゆるい文章では)良いかもしれない。
名詞で使うなら「大食い」とか。

2018-06-23 14:33 UTC, ma2gedev commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
こんな感じではどうでしょうか。

`あらゆるものが並行して仮想マシンの中にあるので、ある特定のプロセス、ドライバー、自前のErlangコード、組み込まれたNIF、あるいはサードパーティのライブラリーのどれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。`

ただ元のものでもそんなに違和感はない気がします。

2018-06-23 14:46 UTC, shino commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
どちらも日本語としての違和感は特に感じませんでした。

一点、文の構造として、With everything concurrent and in a virtual machine, は
and の前後が対等ではないかと思います。つまり「すべてが並列であること」そして「仮想マシンのなかにあること」の両方が CPU usage だけから問題をピンポイントで当てることをむずかしくしている、と言っているのではないかと。どうでしょうか。

2018-06-23 14:48 UTC, ma2gedev commented on 108-cpu-ja.tex
> +実行中のコードの位置\footnote{コードの位置は\expression{recon:info(PidTerm, location)}または\expression{process\_info(Pid, current\_stacktrace)}で取得してください。}や現在の関数を使って、どの種類のコードが全スケジューラをリソースを独占しているか特定できるはずです。
細かいですが、

> 全スケジューラをリソースを独占しているか

は `全スケジューラのリソース` か `全スケジューラリソース` でしょうか。

2018-06-23 15:41 UTC, shino commented on 108-cpu-ja.tex
> +ただし、集中化したグローバルの状態（プロセス辞書やETSテーブルなど）だけは、だいたい変更が必要になります。
分散の妨げになる、という文脈なので中央集権(的)とかどうでしょう。

2018-06-23 16:07 UTC, shino commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
後半難しいですね…

> It's still a decent piece of work, but nothing compared to finding out most of your program's semantics aren't applicable to distributed systems given Erlang usually forces your hand there in the first place.

ぼくの解釈した構造は:

- It's still a decent piece of work, but
- (nothing (compared to finding out most of your program's semantics) aren't applicable to
   distributed systems)
  -  (given Erlang usually forces your hand there in the first place).

ということで、ちょっと意訳かつ3文に分割してみた試訳:

これ(=finding a state-replication scheme that's suitable)は依然として相当な(decent)問題です。
しかし、あなたのプログラムのセマンティクスの大部分を理解することを除いては、分散システムの問題として
重要なこと(applicable)はなにもないのです。
なぜなら、Erlang は最初からあなたの手をそこ(=分散システム)にあるよう強制しているのですから。

これは英語できる人に見てもらいたい。 @ymotongpoo お願いします。

2018-06-23 16:09 UTC, shino commented on 108-cpu-ja.tex
> +あらゆるものが並行する仮想マシンの中では、どれが処理能力を食い尽くしてるかを見つけ出せる保証はありません。
どちらでもこの文脈では違和感ないです。

2018-06-23 16:17 UTC, shino commented on 108-cpu-ja.tex
> +新しいプロファイラの一つです。対象のコードの深い呼び出しシーケンスやホットスポットを可視化するFlame Graphsを生成します。
本家 http://www.brendangregg.com/flamegraphs.html では、本文中、 flame graph(s) と小文字で綴っているので小文字で良いと思います。
日本語の定訳は知らないのでそのままでいいかと。

2018-06-23 16:23 UTC, shino commented
ワンパスレビューしました。英語難しいよ…

2018-06-26 12:33 UTC, ymotongpoo requested changes
いくつかコメントしました

2018-06-26 12:33 UTC, ymotongpoo commented on 108-cpu-ja.tex
> +ノードから抜け出す重要な操作ができなくなることがあります。
自分は単純に「基本的なコードが多ければ多いほどスケールが楽ちん」という解釈をしました

2018-06-26 12:33 UTC, ymotongpoo commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
ここは "the form of sharding" or "the form of finding a state-repliation scheme" で、かつ that's suitable は a state-replication scheme にかかっていると思います。また and little moreは「など」程度の訳になると思います。

2018-06-26 12:33 UTC, ymotongpoo commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
まず given 以下は if と同じような感じであとから付け加えて訳せばいいと思うので一旦忘れます。で、構造は僕も篠原さんと同じ解釈です。ただ it の解釈が違って、僕は前の文のそのものと解釈しました。つまり状態の中央集権化の解消（shardingやfinding〜）というのは依然として大変な問題だ、というところから話が始まって、 but 以下は篠原さんと同じ解釈です。

2018-06-26 13:40 UTC, tkyshm commented on 108-cpu-ja.tex
> +\footnote{通常、これはシャーディングの形を取るか、状態のレプリケーションスキームを見つけるのが適してます。最初、Erlangがきっかけで分散システムを作るが、その分散システムは大部分のプログラムのセマンティクスに適用できないと分かる。それに比べると、これらの方法はまだ適切です。}
@shino @ymotongpoo 分かりやすいコメントありがとうございます

解釈としてはこんな感じに頭の中でまとまりました。
```
あなたのプログラムのセマンティクスの大部分を理解することに比べれば、分散システムへの適用は大した問題にはなりません。何故なら、最初にErlangは分散システムを強要するからです。
```

2018-06-30 14:15 UTC, ymotongpoo requested changes
翻訳そのものよりも、編集に関するコメントです。

2018-06-30 14:15 UTC, ymotongpoo commented on 108-cpu-ja.tex
> +それでも、スケールアウトする前にローカルで最適化したい場合は、CPUとスケジューラの大量消費を見つけ出だす必要があります。
typo:見つけ出だす

2018-06-30 14:15 UTC, ymotongpoo commented on 108-cpu-ja.tex
> +既存のアプローチは大体限られており、コード内にある場合はプロファイリングとリダクションカウント\footnote{プロセスごとにリダクションというカウンタがあり、このカウンターは通常一つの各関数呼び出しでインクリメントされます。このリダクション回数が最大値に達した時、コンテキストスイッチが発生します。\href{http://erlang.org/doc/man/erlang.html\#bum
訳注をする場合は訳注を明記してください。（現状だと訳文だけで筆者が記述したものかどうかの判断がつきません。）

2018-07-12 04:43 UTC, shino commented
@ymotongpoo これは approve 待ちかも?

2018-07-16 01:27 UTC, ymotongpoo approved these changes

2018-07-16 01:27 UTC, merged