103: 3.3.3 Stack Buffers 翻訳
ymotongpoo/erlang-in-anger pull request #49
Opened 2018-06-29 08:03 UTC by yaoshimax

## 翻訳スコープ
- 3.3.3「Stack Buffers」

## マージ目安
どちらかが達成されたらマージしようと思ってます

- [ ] 誰か１人からLGTMをもらう

もしくは、

- [ ] 2018/07/01 12:00(JST) をすぎる
- [ ] 訳者の不安な部分が解消される（＝TODOコメントがなくなる）

2018-07-01 05:32 UTC, hykw commented
LGTM

2018-07-01 06:11 UTC, shino requested changes
レビューコメント入れました。単純なものだけです。

2018-07-01 06:11 UTC, shino commented on 103-overload-ja.tex
> +スタックをバッファとして利用するには、キューバッファの時のように二つのプロセスが必要となりますが、キュー構造の代わりにリスト\footnote{どうでも良いことですが、Erlangではリスト\emph{が}スタックです。ErlangリストはO(1)の計算量でpushとpop操作を提供していて、非常に早いです。}が使われます。
早い → 速い

2018-07-01 06:11 UTC, shino commented on 103-overload-ja.tex
> +低レイテンシのためにスタックバッファが特に優れている理由は、バッファブロート\footnote{\href{http://queue.acm.org/detail.cfm?id=2071893}{http://queue.acm.org/detail.cfm?id=2071893 }}に似た問題と関係しています。キューバッファにある少量のメッセージが遅れると、キューの中にあるすべてのメッセージに
> 少量のメッセージが遅れると

遅れるのはメッセージではなく、you=処理側で訳すほうが繋がりが良いかと思います。

2018-07-01 06:11 UTC, shino commented on 103-overload-ja.tex
> +その一方で、スタックはある一定数の要素だけが待たされて、新しい方からタイムリーにサーバで処理されます。% TODO: 要はLIFOってことを言いたいだけだと思うんですが、stackでもqueueでも一定数の制限を設けることはできるよなぁ…と思い、前半の文意を少し捉えかねています
要は LIFO ってのはそのとおりですね。
スタックを入れるときの嬉しさは、数の制限を入れるのではなくて、(ある程度メッセージを捨てることになるとしても)、応答時間が短く保てるメッセージを増やせる、というところです。
過負荷になっていないときはどっちでも同じなので、
1. ちょうどサービス能力とメッセージ流量がおなじになってしまった場合(メッセージ一つの処理に 1msec, メッセージ到着も 1msec 毎)で、
2. あるひとつのメッセージAだけが5msecかかってしまったという状況

キューの場合、 A の処理中にB,C,D,E が到着します。すると、B の応答時間は A を処理と重なる 4 msec + 自分の 1msec で5msecかかります。
同様に C も 5 msec, ... です。

一方、スタックにすると、Aに5msecかかったとしても、B,C,D,E は一旦スタックに入ってしまって、Aが終わったあと
E が処理され、それは A の処理と重なる 1msec + 自分の 1msec で 2msec。 そのうちに F が来て、それが(だいたい)1msec で
応答されます。B,C,D は悲しいことになりますが、応答時間の SLA がキツイときにはこっちのほうがSLAを守れる率が高くなることがある。

以上、ちょっとシンプルさのためにキワを仮定しすぎていますが、おおざっぱにはこんなかんじかと。

2018-07-01 06:11 UTC, shino commented on 103-overload-ja.tex
> +その一方で、スタックはある一定数の要素だけが待たされて、新しい方からタイムリーにサーバで処理されます。% TODO: 要はLIFOってことを言いたいだけだと思うんですが、stackでもqueueでも一定数の制限を設けることはできるよなぁ…と思い、前半の文意を少し捉えかねています
ちなみに訳に関してはいまのままで問題ないと思います ;)

2018-07-02 03:51 UTC, yaoshimax commented on 103-overload-ja.tex
> +その一方で、スタックはある一定数の要素だけが待たされて、新しい方からタイムリーにサーバで処理されます。% TODO: 要はLIFOってことを言いたいだけだと思うんですが、stackでもqueueでも一定数の制限を設けることはできるよなぁ…と思い、前半の文意を少し捉えかねています
ありがとうございます！
「number of elements are kept waiting waiting」の意味をキューorスタックに溜まっている数…？と少し混乱してましたが、
応答時間が長くなってしまうメッセージの数、と考えればスッキリ意味が通りますね。

混乱してた割に訳文は文意に沿っているように思うので、このままにしようと思いますー

2018-07-02 05:01 UTC, shino approved these changes
修正ありがとうございました。
LGTM 👍

2018-07-02 05:19 UTC, yaoshimax commented
レビューありがとうございました、マージさせていただきますー！

2018-07-02 05:19 UTC, merged