WIP: translate 7.3.2 Erlang's Memory Model
ymotongpoo/erlang-in-anger pull request #52
Opened 2018-07-01 14:08 UTC by ma2gedev

## 翻訳スコープ

7.3.2 Erlang's Memory Model

## 気になるところ

アロケーション戦略のところを訳すべきか訳さぬべきか。。。今は訳さない方に寄せています。

- Best fit -> ベストフィット
  - わかる
- Address order best fit -> アドレス順ベストフィット
  - わかる 🤔 
- Address order first fit carrier best fit -> アドレス順ファーストフィットキャリアベストフィット
  - 😇 

その他コメント入れます。

2018-07-08 11:47 UTC, ma2gedev commented
conflict していたので一旦 rebase しました。また `VerbatimText` ないのコメントアウトができなかったのでオリジナルのテキストを d460eee734c370ea7b8f92f1eb0d644a2e7fa486 で削除しています。

2018-07-10 01:13 UTC, shino requested changes
長いセクションの訳おつかれさまです。僕にとってはとても勉強になりました 😄 
いくつかコメント入れましたので確認してもらえるとありがたいです 🚀

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +メモリがどこへ行くのか理解するために、たくさんのメモリアロケータが使われていることを最初に理解しなければならない。VM 全体のためのErlangのメモリモデルは階層的になっています。\ref{fig:allocators}の図にあるように、2つのメインとなるアロケータがあり、他にサブアロケータ(1−9までの番号が付けられた)があります。サブアロケータはErlangコードとVMから使われるほとんど
細かくてすみませんが、最初の文だけ「だである」なので「ですます」で他と合わせるのが良いです

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +    \item \term{binary\_alloc}: リファレンスカウントされたバイナリ(グローバルヒープにある)に使われるアロケータ。ETSテーブルに格納されたリファレンスカウントされたバイナリはこのアロケータに残ります。
メモリの分割統治の文脈なので、「グローバルヒープ」と(括弧やクォート無しで)書くと、そういうヒープ領域があるようにも読めてしまいました。原文のシングルクォートの気持ちがにじみ出ると良いと思うのですが。しかしちょっと難しい。

ぼくの解釈は、次のとおりです。Erlang コードから見た単純なビューとして (つまり、VM の構造/実装をあまり深く考えない場合)、バイナリはすべてのプロセスで共有されて、参照だけプロセスヒープに持つように見えている。この、「すべてのプロセスで共有されている」というのを 「Eralng プロセスを跨いだ領域」という意味で 'global heap' と呼んでいると。

これを踏まえて、例えばですが次のような訳を考えてみました。

1. Erlang プロセスで共有される「グローバルなヒープ」そのもの
2. バイナリのための「グローバルなヒープ」のこと

いかがでしょうか。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +    \item \term{fix\_alloc}: 頻繁に使われる固定サイズのメモリブロックのために使われるアロケータ。ここで使われるデータの1つとしてはVMで内部的に使われている内部プロセスのC構造体があります。
> 内部プロセスのC構造体があります。

内部がプロセスにかかるようにも読めるので、C struct にかかるように訳せると良いかもしれません。
直前に「内部的に」とあるので、単に「内部」を取ってしまっても良いかと思います。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +デフォルトでは、スケジューラごとに各アロケータのインスタンスが1つずつ(そしてコアごとに1つのスケジューラを持つはずです)、加えて非同期のスレッドを使うリンクされたドライバーで使われるインスタンスが一つあります。これは\ref{fig:allocators}の図にあるような構造をあなた与えますが、それぞれの葉で\var{N}個の部分に分かれます。
linked-in driver は「すごいErlang...」でそのまま使われていたので、こっちでも合わせてそのまま英語で良いかと。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +デフォルトでは、スケジューラごとに各アロケータのインスタンスが1つずつ(そしてコアごとに1つのスケジューラを持つはずです)、加えて非同期のスレッドを使うリンクされたドライバーで使われるインスタンスが一つあります。これは\ref{fig:allocators}の図にあるような構造をあなた与えますが、それぞれの葉で\var{N}個の部分に分かれます。
> 構造をあなた与えますが

タイポでしょうか。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +これらのサブアロケータはユースケースに応じて\term{mseg\_alloc}と\term{sys\_alloc}の2つあるうちのどちらかからメモリを要求します。最初の方法はマルチブロックキャリア(\term{mbcs})として行動します。それは多数のErlang項のために使われるメモリの塊を一度に取得します。それぞれの\term{mbc}のために、VMは与えられたメモリ量(我々の場合はデフォ
`in two possible ways` は `from \term{mseg\_alloc} and \term{sys\_alloc}` とは独立なのではないかと思います。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +マルチブロックキャリア(または最初の\term{mmsbc}\footnote{\href{http://erlang.org/doc/man/erts\_alloc.html\#M\_mmsbc}{http://erlang.org/doc/man/erts\_alloc.html\#M\_mmsbc}}シングルブロックキャリア)が再利用できる時はいつでも、\term{mseg\_alloc}
> 毎回もっとと

タイポ?

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +\emph{Address order best fit}(\term{aobf})は似たように働きますが、代わりに木はブロックのアドレスに基づきます。VMはデータが格納できる利用可能な最も小さなブロックを探しますが、もし同じサイズのものがたくさんある場合は、ブロックのアドレスがより低いものを選びます。3つのブロックを必要とするデータがある場合、またエリア3となりますが、もし2つのブロックが必要
> これによりVMは多くの割り当てに対し、同じキャリアを優先する傾向を持たせられます。

VM に...傾向をもたせられる、という構造です。「VM は」を主語にするなら、「傾向を持つことができます」「傾向を持つようになります」「傾向になります」という訳になるでしょうか。どちらでも良いと思います。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +その領域はスタックかヒープが何も格納できなくなるまでもっと割り当てられる。これはマイナーGCを引き起こします。マイナーGCはオールド領域のヒープに保持できるデータを動かします。そして残りを集め、さらなる領域を再割り当てするかもしれません。
「割り当てられる。」 <= ここも「ですます」でいきましょう。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +その領域はスタックかヒープが何も格納できなくなるまでもっと割り当てられる。これはマイナーGCを引き起こします。マイナーGCはオールド領域のヒープに保持できるデータを動かします。そして残りを集め、さらなる領域を再割り当てするかもしれません。
> It then collects the rest

GC の C なので「集める」より「回収する」のほうが通りが良いかもです。

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +それが起こると時間の80\%以上はメモリはサブアロケータで利用可能とマークされ、リサイズが必要な新しいプロセスまたは他のプロセスによって取り戻せるようになります。このメモリが使われていない --- マルチブロックキャリアもまた使われていない --- 状態になった後でのみ、しばらくの間それが保持されていてもいなくてもよいが\term{mseg\_alloc}または\term{sys\_alloc}
> リサイズが必要な新しいプロセスまたは他のプロセスによって

新しいプロセスまたはリサイズが必要な他のプロセスによって

2018-07-10 01:13 UTC, shino commented on 107-memory-leaks-ja.tex
> +それが起こると時間の80\%以上はメモリはサブアロケータで利用可能とマークされ、リサイズが必要な新しいプロセスまたは他のプロセスによって取り戻せるようになります。このメモリが使われていない --- マルチブロックキャリアもまた使われていない --- 状態になった後でのみ、しばらくの間それが保持されていてもいなくてもよいが\term{mseg\_alloc}または\term{sys\_alloc}
> しばらくの間それが保持されていてもいなくてもよいが\term{mseg\_alloc}または\term{sys\_alloc}へ返されます。

カンマ+which なので、係り受けではなくて素直に時系列で訳してもいいと思います。例えば


> \term{mseg\_alloc}または\term{sys\_alloc}へ返され、それはしばらくの間それが保持されたりされなかったりします。

2018-07-11 01:07 UTC, ma2gedev commented
いつもフィードバックありがとうございます。今日帰ったら反映していきます！

2018-07-11 15:49 UTC, ma2gedev commented
結構な量があるのに見ていただきありがとうございます。
一通り対応してみました。

2018-07-12 04:40 UTC, shino approved these changes

2018-07-12 04:41 UTC, shino commented
多くの修正をきっちりやってもらってありがとうございました!
LGTM 👍

2018-07-12 15:46 UTC, merged