add 103
ymotongpoo/erlang-in-anger pull request #57
Opened 2018-07-23 14:12 UTC by spinute

2018-08-26 21:56 UTC, ymotongpoo commented on 103-overload-ja.tex
> +このデグレの背後にある原因は、リモートサーバーが落ちたときに、突然すべての接続操作が最低10ミリ秒かかるようになったことでした。この10ミリ秒は接続試行が断念されるまでの時間です。中央のプロセスに秒間9,000メッセージが届くようになったあたりでは、各接続試行は通常5ミリ秒以下で、この障害と同様の状況になったのは、およそ秒間18,000メッセージが届くようになったあたりで、このあたりで手に負えな
後半の修正は「このあたりで」が余計？

2018-08-26 21:58 UTC, ymotongpoo commented on 103-overload-ja.tex
> +プログラム内でメッセージを受信するための中央的なハブになっている場所が\emph{一つでも}あれば、時間がかかるタスクはそこから出来る限り取り除くべきでしょう。
出来る「限り」の語感はないように感じます

2018-08-26 21:59 UTC, ymotongpoo requested changes
細かな点1点だけ確認お願いします。

2019-01-19 10:03 UTC, spinute commented on 103-overload-ja.tex
> +このデグレの背後にある原因は、リモートサーバーが落ちたときに、突然すべての接続操作が最低10ミリ秒かかるようになったことでした。この10ミリ秒は接続試行が断念されるまでの時間です。中央のプロセスに秒間9,000メッセージが届くようになったあたりでは、各接続試行は通常5ミリ秒以下で、この障害と同様の状況になったのは、およそ秒間18,000メッセージが届くようになったあたりで、このあたりで手に負えな
"...and things got out of hand" を「...、このあたりで事態が手に負えなくなった」と解釈していました。

もともとの訳文後半「...、この障害と同様の状況になったのは、およそ秒間18,000メッセージが届くようになったあたりで手に負えなくなりました。」は文になっていないのではないかと思います。

上手く訳すにはもう少し大胆に手を入れる必要があると思うのですが、この一連の PR ではあまり大きな修正は入れないようにしたいので、いったん元に戻します。

2020-04-12 11:56 UTC, merged