add 101
ymotongpoo/erlang-in-anger pull request #59
Opened 2018-07-23 14:13 UTC by spinute

2018-08-26 21:48 UTC, ymotongpoo commented on 101-diving-ja.tex
> +OTPリリースは複数のOTPアプリケーションを本番投入可能な状態でパッケージ化したもので、その結果、起動する際に手動でアプリケーションの\function{application:start/2}を呼び出さずに済むようになっています。
> it boots and shuts down

shuts downが抜けています

2018-08-26 21:49 UTC, ymotongpoo requested changes
時間がかかってしまってすみません。1点確認をお願いします。

2018-09-09 07:18 UTC, y-yu commented
@spinute 

どうでしょうか？

2019-01-19 09:43 UTC, spinute commented on 101-diving-ja.tex
> +OTPリリースは複数のOTPアプリケーションを本番投入可能な状態でパッケージ化したもので、その結果、起動する際に手動でアプリケーションの\function{application:start/2}を呼び出さずに済むようになっています。
start・stop を呼ばなくても起動・終了をしてくれる、というようなことを書いているのだと思いますが、原文には `application:start/2` しか出ていないので、並列した記述の粒度を揃えようとして終了に関する記述を省いたような気がします。

原文のままにする、stop を足す、終了を削る、の選択肢があるところですが、判断できないためとりあえず元に戻すことにします。

2019-01-19 09:47 UTC, spinute commented
@ymotongpoo さん、@y-yu さん

返信が非常に遅くなってしまいまして申し訳ありません。コメントを頂いた箇所について、今日中を目処に修正や返信を書きます。

2020-04-12 11:53 UTC, y-yu commented
@ymotongpoo さん。

僕自身はちょっとこの本の内容に直接関わっているわけではないので、ちょっとまあ静観してたんですが、せっかくの修正ですしApproveできませんかね？
#58 #57 もそうですが、いまさら感があるけどちょっと放置になってしまって申し訳ないので……。

2020-04-12 11:54 UTC, ymotongpoo commented
すいません、普通に既読にしちゃったままでした。マージしますね。

2020-04-12 11:55 UTC, merged

2020-04-12 11:59 UTC, y-yu commented
こんなことならもっと早くいえばよかった…… 😇 僕の方からも、せっかくの貢献なのに放置してしまったことに謝罪したいと思います 🙇